### ISSUE TITLE
I love PHP

### ISSUE THREAD

**Issue by taeguk** [SGCSRelease/lab_management#4]
뻥임.

**Comment by minhoryang** [comment]
I don't know why

**Comment by juice500ml** [comment]
:-1:

**Comment by minhoryang** [comment]
I hate PHP, but when I do, I use HHVM PHP.

**Comment by taeguk** [comment]
힙합!

**Comment by mandoriiiii** [comment]
댓글

**Comment by taeseunglee** [comment]
권태국 권태국 권태국 권태국

**Comment by taeguk** [comment]
@SGsupernova loves Linux and Vim.

If he have to do Windows Programming, maybe he writes codes using vim in linux and does remote debugging.... kikiki

**Comment by minhoryang** [comment]
LGTM
